### ISSUE TITLE
Make links in Useful Resources and References live links

### ISSUE THREAD

**Issue by dougierad** [duckietown/docs-duckiesky_high_school#25]
It would be nice if the links in the Useful Resources and References section at the end of each lesson were live links. They are now just static text.

**Comment by dougierad** [comment]
I noticed this in the Importance of Robotics lessons.

**Comment by GarrettWarren** [comment]
Thanks for this issue! The links in this lesson should be working now! I checked the subsequent lessons and they seem to be working now, too. Let us know if you have another issue in other lessons
